# Generated by Django 4.0.4 on 2022-05-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_delete_student_alter_ativo_formador_mercado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotacao',
            name='nome_ativo',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='cotacao',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='nome_ativo',
        ),
        migrations.DeleteModel(
            name='Ativo',
        ),
        migrations.DeleteModel(
            name='Cotacao',
        ),
        migrations.DeleteModel(
            name='Operacao',
        ),
    ]
